project:
  name: cardboardlint
  packages:
    - dist_name: cardboardlint
      tools:
        - write-py-version
        - test-example
        - cardboardlint-static
        - cardboardlint-dynamic
        - pytest
        - upload-codecov
        - build-py-source
        - build-conda
        - deploy-pypi
        - deploy-conda
        - deploy-github
tools:
  # override the default config, add pip install from current directory
  cardboardlint-static:
    commands_master:
      - pip install .
      - cardboardlinter -f static -n auto
    commands_feature:
      - pip install .
      - 'cardboardlinter -r {config.git.merge_branch} -f static -n auto'

  # override the default config, add pip install from current directory
  cardboardlint-dynamic:
    commands_master:
      - pip install .
      - cardboardlinter -f dynamic -n auto
    commands_feature:
      - pip install .
      - 'cardboardlinter -r {config.git.merge_branch} -f dynamic -n auto'

  # new tool, to run on the example directory
  test-example:
    cls: TestInPlace
    requirements:
      - [coverage, coverage]
    commands:
      - pip install .
      - cd tools/example; coverage erase;
        coverage run --include=*cardboardlint* --omit=*poor* -m cardboardlint -n auto;
        coverage xml -i -o ../../coverage_examples_linter.xml
      - cp -r tools/example tools/work
      - cd tools/work; coverage erase;
        coverage run --include=*cardboardlint* --omit=*poor* -m cardboardlint -n auto -F;
        coverage xml -i -o ../../coverage_examples_fixer.xml
      - rm -vrf tools/work
